services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=symmy_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: >
      sh -c "
      sleep 10 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: >
      sh -c "
      sleep 10 &&
      celery -A core worker --loglevel=info
      "
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis